import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';

import { JobApplication, JobApplicationService, Resume } from '../../core/services/jobApplication.service';
import { AuthService, SubscriptionStatus } from '../../core/services/auth.service';
import { ProfileService } from '../../core/services/profile.service';
import { ExperienceService } from '../../core/services/experience.service';
import { ProjectService } from '../../core/services/project.service';

type SectionKey = 'summary' | 'skills' | 'experience' | 'projects';

@Component({
  selector: 'app-tailoring-workspace',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    @if (loading()) {
      <div class="workspace-loading">Loading workspace...</div>
    } @else {
      <div class="workspace">
        <div class="ws-header">
          <button class="back-link" (click)="goBack()">← Back to board</button>
          <div class="ws-title">
            <h2>{{ application()?.jobTitle }}</h2>
            <p class="company">{{ application()?.company?.name || 'Unknown Company' }}</p>
          </div>
          <span class="status-pill" [attr.data-status]="application()?.status">{{ application()?.status }}</span>
          @if (quota?.isActive) {
            <div class="quota-hint">{{ quota?.aiGenerations || 0 }}/{{ quota?.aiQuota || 30 }} AI generations used this period</div>
          }
        </div>

        @if (toast) {
          <div class="toast">{{ toast }}</div>
        }

        <div class="action-bar">
          <button class="primary" [disabled]="tailoring()" (click)="tailor()">
            @if (tailoring()) { Tailoring... } @else { ✨ Tailor My Resume }
          </button>

          @if (resumes().length > 0) {
            <select class="version-select" (change)="onVersionChange($event)">
              @for (r of resumes(); track r.id) {
                <option [value]="r.id" [selected]="r.id === activeResume()?.id">Version {{ r.version }}{{ isLatest(r) ? ' (latest)' : '' }}</option>
              }
            </select>
          }

          @if (activeResume() && !isLatest(activeResume())) {
            <button class="ghost" [disabled]="restoringId === activeResume()!.id" (click)="restore(activeResume()!.id)">
              @if (restoringId === activeResume()!.id) { Restoring... } @else { Restore this version }
            </button>
          }

          @if (activeResume() && (activeResume()!.matchScore === null || dirty())) {
            <button class="secondary" [disabled]="reanalyzing()" (click)="reanalyze()">
              @if (reanalyzing()) { Checking... } @else { Re-check Fit }
            </button>
          }

          <button class="export-btn" [disabled]="!activeResume() || exporting()" (click)="exportPDF()">
            @if (exporting()) { Exporting... } @else { ⬇ Export PDF }
          </button>
        </div>

        <p class="disclaimer">
          Resume content is generated by Google Gemini AI. We do not guarantee accuracy.
          You are responsible for reviewing all AI-generated content before submitting it to any employer.
        </p>

        @if (!activeResume()) {
          <div class="empty-state">
            <p>No resume yet for this application. Click "Tailor My Resume" to generate one.</p>
          </div>
        } @else {
          <div class="split-body">
            <div class="pane jd-pane">
              <h3>Job Description</h3>
              <div class="jd-text">{{ application()?.jobDescription }}</div>
            </div>

            <div class="pane resume-pane">
              <div class="fit-card">
                <div class="fit-header">
                  <strong>Fit Analysis</strong>
                  @if (activeResume()!.matchScore !== null) {
                    <span class="score-badge">{{ activeResume()!.matchScore }}%</span>
                  }
                  @if (dirty()) {
                    <span class="stale-hint">Score may be outdated — Re-check Fit</span>
                  }
                </div>
                @if (parsedBreakdown()) {
                  <div class="breakdown">
                    @if (parsedBreakdown().skills !== undefined) { <span>Skills: {{ parsedBreakdown().skills }}%</span> }
                    @if (parsedBreakdown().experience !== undefined) { <span>Experience: {{ parsedBreakdown().experience }}%</span> }
                    @if (parsedBreakdown().projects !== undefined) { <span>Projects: {{ parsedBreakdown().projects }}%</span> }
                    @if (parsedBreakdown().summary !== undefined) { <span>Summary: {{ parsedBreakdown().summary }}%</span> }
                  </div>
                }
                @if (activeResume()!.suggestions) {
                  <p class="suggestions">{{ activeResume()!.suggestions }}</p>
                }
                @if (parsedMissingSkills().length) {
                  <div class="chips">
                    @for (kw of parsedMissingSkills(); track kw) {
                      <span class="chip chip-bad">{{ kw }}</span>
                    }
                  </div>
                }
                @if (activeResume()!.matchScore === null && !parsedBreakdown()) {
                  <p class="muted">No fit analysis yet.</p>
                }
              </div>

              <div class="resume-content">
                <div class="section-block">
                  <div class="section-head">
                    <h4>Summary</h4>
                    @if (isLatest(activeResume())) {
                      <button class="regen-btn" [disabled]="sectionBusy['summary']" (click)="regenerateSection('summary')">
                        @if (sectionBusy['summary']) { ⏳ } @else { ↻ Regenerate }
                      </button>
                    }
                  </div>
                  <p>{{ parsedContent()?.summary }}</p>
                </div>

                <div class="section-block">
                  <div class="section-head">
                    <h4>Skills</h4>
                    @if (isLatest(activeResume())) {
                      <button class="regen-btn" [disabled]="sectionBusy['skills']" (click)="regenerateSection('skills')">
                        @if (sectionBusy['skills']) { ⏳ } @else { ↻ Regenerate }
                      </button>
                    }
                  </div>
                  <div class="chips">
                    @for (s of parsedContent()?.skills || []; track s) {
                      <span class="chip">{{ s }}</span>
                    }
                  </div>
                </div>

                @if (parsedContent()?.experience?.length) {
                  <div class="section-block">
                    <h4>Experience</h4>
                    @for (exp of parsedContent().experience; track exp.company + exp.role + $index; let i = $index) {
                      <div class="entry">
                        <div class="entry-head">
                          <div>
                            <strong>{{ exp.role }}</strong> <span class="muted">&#64; {{ exp.company }}</span>
                            <span class="dates">{{ exp.start }} - {{ exp.end || 'Present' }}</span>
                          </div>
                          @if (isLatest(activeResume())) {
                            <button class="regen-btn" [disabled]="sectionBusy['experience:' + i]" (click)="regenerateSection('experience', i)">
                              @if (sectionBusy['experience:' + i]) { ⏳ } @else { ↻ }
                            </button>
                          }
                        </div>
                        @if (exp.bullets?.length) {
                          <ul>
                            @for (b of exp.bullets; track b) { <li>{{ b }}</li> }
                          </ul>
                        }
                      </div>
                    }
                  </div>
                }

                @if (parsedContent()?.projects?.length) {
                  <div class="section-block">
                    <h4>Projects</h4>
                    @for (proj of parsedContent().projects; track proj.title + $index; let i = $index) {
                      <div class="entry">
                        <div class="entry-head">
                          <strong>{{ proj.title }}</strong>
                          @if (isLatest(activeResume())) {
                            <button class="regen-btn" [disabled]="sectionBusy['projects:' + i]" (click)="regenerateSection('projects', i)">
                              @if (sectionBusy['projects:' + i]) { ⏳ } @else { ↻ }
                            </button>
                          }
                        </div>
                        @if (proj.bullets?.length) {
                          <ul>
                            @for (b of proj.bullets; track b) { <li>{{ b }}</li> }
                          </ul>
                        }
                      </div>
                    }
                  </div>
                }

                @if (parsedContent()?.education?.length) {
                  <div class="section-block">
                    <h4>Education</h4>
                    @for (edu of parsedContent().education; track edu.institution + edu.degree) {
                      <p>{{ edu.degree }} in {{ edu.field }} — {{ edu.institution }} ({{ edu.start }} - {{ edu.end }})</p>
                    }
                  </div>
                }

                @if (parsedContent()?.certifications?.length) {
                  <div class="section-block">
                    <h4>Certifications</h4>
                    <ul>
                      @for (c of parsedContent().certifications; track c.title) { <li>{{ c.title }}</li> }
                    </ul>
                  </div>
                }
              </div>
            </div>
          </div>
        }

        @if (isAdmin) {
          <div class="debug-panel">
            <button class="debug-toggle" (click)="showDebugPanel = !showDebugPanel">
              {{ showDebugPanel ? 'Hide' : 'Show' }} Debug / Admin Tools
            </button>
            @if (showDebugPanel) {
              <div class="debug-body">
                <div class="debug-row">
                  <select [(ngModel)]="selectedModel">
                    @for (m of models; track m) { <option [value]="m">{{ m }}</option> }
                  </select>
                  <button class="small" [disabled]="legacyGenerating" (click)="legacyGenerate()">
                    @if (legacyGenerating) { Generating... } @else { Legacy Generate (no analysis) }
                  </button>
                  <button class="small ghost" (click)="togglePromptEditor()">Customize Prompt</button>
                  <button class="small ghost" (click)="copyPrompt()">Copy Prompt</button>
                  <button class="small ghost" (click)="startImport()">Import Resume</button>
                  <button class="small ghost" (click)="toggleRaw()">{{ showRaw ? 'Hide' : 'Show' }} Raw JSON</button>
                </div>

                @if (showPromptEditor) {
                  <div class="prompt-editor">
                    <textarea [(ngModel)]="promptDraft" rows="6"></textarea>
                    <div class="prompt-actions">
                      <button class="small primary" (click)="saveCustomPrompt()">Save</button>
                      <button class="small ghost" (click)="resetCustomPrompt()">Reset to default</button>
                    </div>
                  </div>
                }

                @if (importingOpen) {
                  <div class="import-panel">
                    <textarea [(ngModel)]="importContent" rows="8" placeholder="Paste resume JSON..."></textarea>
                    <div class="import-actions">
                      <button class="small primary" (click)="submitImport()">Import</button>
                      <button class="small ghost" (click)="cancelImport()">Cancel</button>
                    </div>
                  </div>
                }

                @if (showRaw && activeResume()) {
                  <pre class="raw-json">{{ activeResume()!.content | json }}</pre>
                }
              </div>
            }
          </div>
        }
      </div>
    }
  `,
  styles: `
    .workspace-loading { text-align: center; padding: 60px; color: #666; }

    .workspace { max-width: 1200px; margin: 0 auto; padding: 20px; }

    .ws-header {
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap: 12px;
      margin-bottom: 12px;
    }

    .back-link {
      background: none;
      color: #667eea;
      padding: 4px 0;
      font-size: 14px;
      cursor: pointer;
    }

    .ws-title { flex: 1; min-width: 200px; }
    .ws-title h2 { margin: 0; }
    .company { margin: 2px 0 0; color: #555; font-weight: 600; }

    .status-pill {
      padding: 4px 10px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      color: white;
      background: #6c757d;

      &[data-status="applied"] { background: #007bff; }
      &[data-status="interviewing"] { background: #ffc107; color: #333; }
      &[data-status="offer"] { background: #28a745; }
      &[data-status="rejected"] { background: #dc3545; }
    }

    .quota-hint { font-size: 12px; color: #888; width: 100%; }

    .toast {
      background: #e6f4ea;
      border: 1px solid #a7e0b5;
      color: #1e7e34;
      border-radius: 6px;
      padding: 10px 14px;
      margin-bottom: 12px;
      font-size: 14px;
      font-weight: 600;
    }

    .action-bar {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      align-items: center;
      margin-bottom: 10px;
    }

    button {
      padding: 9px 16px;
      border: none;
      border-radius: 6px;
      background: #f1f3f5;
      color: #333;
      cursor: pointer;
      font-size: 14px;

      &.primary { background: linear-gradient(135deg, #667eea, #764ba2); color: white; font-weight: 600; }
      &.secondary { background: #eef1ff; color: #4c51bf; }
      &.ghost { background: #f1f3f5; color: #333; border: 1px solid #ddd; }
      &.export-btn { background: #28a745; color: white; }
      &.small { padding: 6px 10px; font-size: 12px; }
      &:disabled { opacity: 0.6; cursor: not-allowed; }
    }

    .version-select {
      padding: 8px 10px;
      border: 1px solid #ddd;
      border-radius: 6px;
      font-size: 13px;
    }

    .disclaimer {
      font-size: 12px;
      color: #888;
      margin: 0 0 16px;
    }

    .empty-state {
      text-align: center;
      padding: 60px 20px;
      color: #777;
      background: #f8f9fa;
      border-radius: 10px;
    }

    .split-body {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1.5rem;
    }

    .pane {
      background: white;
      border-radius: 10px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.08);
      padding: 16px;
      max-height: 75vh;
      overflow-y: auto;
    }

    .jd-pane h3 { margin-top: 0; }
    .jd-text { white-space: pre-wrap; color: #444; font-size: 14px; line-height: 1.6; }

    .fit-card {
      border: 1px solid #b6d4fe;
      background: #f1f8ff;
      border-radius: 8px;
      padding: 12px;
      margin-bottom: 14px;
    }

    .fit-header { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
    .score-badge {
      background: #e7f3ff;
      color: #004085;
      border: 1px solid #99caff;
      border-radius: 12px;
      padding: 2px 10px;
      font-size: 13px;
      font-weight: 700;
    }
    .stale-hint { font-size: 12px; color: #b45309; }

    .breakdown { display: flex; flex-wrap: wrap; gap: 10px; font-size: 12px; color: #444; margin-top: 6px; }
    .suggestions { font-size: 13px; color: #333; white-space: pre-wrap; margin: 8px 0 0; }

    .chips { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 8px; }
    .chip { background: #e7f3ff; color: #004085; border: 1px solid #99caff; border-radius: 12px; padding: 2px 10px; font-size: 12px; }
    .chip-bad { background: #fee2e2; color: #991b1b; border-color: #fca5a5; }

    .section-block { margin-bottom: 18px; }
    .section-head { display: flex; justify-content: space-between; align-items: center; }
    .section-block h4 { margin: 0 0 6px; font-size: 14px; color: #333; }

    .regen-btn {
      background: none;
      color: #667eea;
      border: 1px solid #d8dcff;
      padding: 3px 8px;
      font-size: 12px;
      border-radius: 12px;
    }

    .entry { margin-bottom: 10px; padding-bottom: 8px; border-bottom: 1px dashed #eee; }
    .entry-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 8px; font-size: 13px; }
    .dates { color: #888; margin-left: 8px; }
    .muted { color: #777; }
    ul { margin: 6px 0 0; padding-left: 18px; }

    .debug-panel { margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px; }
    .debug-toggle { background: none; color: #999; font-size: 12px; text-decoration: underline; }
    .debug-body { margin-top: 10px; background: #fafafa; border: 1px solid #eee; border-radius: 8px; padding: 12px; }
    .debug-row { display: flex; flex-wrap: wrap; gap: 8px; }
    .debug-row select { padding: 6px 8px; font-size: 12px; }

    .prompt-editor, .import-panel { margin-top: 10px; }
    .prompt-editor textarea, .import-panel textarea {
      width: 100%;
      padding: 8px;
      border-radius: 4px;
      border: 1px solid #ccc;
      font-family: monospace;
      font-size: 12px;
      resize: vertical;
    }
    .prompt-actions, .import-actions { display: flex; gap: 8px; margin-top: 8px; }

    .raw-json {
      margin-top: 10px;
      white-space: pre-wrap;
      font-size: 11px;
      background: #f6f6f6;
      padding: 10px;
      border-radius: 4px;
      border: 1px solid #eee;
      max-height: 300px;
      overflow-y: auto;
    }

    @media (max-width: 768px) {
      .workspace { padding: 12px; }
      .split-body { grid-template-columns: 1fr; }
      .pane { max-height: none; }
      input, textarea, select { font-size: 16px; }
      button { min-height: 40px; }
    }
  `
})
export class TailoringWorkspaceComponent implements OnInit {
  applicationId!: number;
  application = signal<JobApplication | null>(null);
  resumes = signal<Resume[]>([]);
  activeResume = signal<Resume | null>(null);

  loading = signal(true);
  tailoring = signal(false);
  reanalyzing = signal(false);
  exporting = signal(false);
  restoringId: number | null = null;
  sectionBusy: Record<string, boolean> = {};
  dirty = signal(false);
  toast: string | null = null;

  isAdmin = false;
  showDebugPanel = false;
  quota: SubscriptionStatus | null = null;

  models = [
    'gemini-2.5-flash',
    'gemini-2.5-flash-lite',
    'gemini-2.5-flash-tts',
    'gemini-3-flash',
    'gemma-3-27b-it'
  ];
  selectedModel = 'gemini-2.5-flash';
  showPromptEditor = false;
  promptDraft = '';
  customPrompt = '';
  legacyGenerating = false;
  importingOpen = false;
  importContent = '';
  showRaw = false;

  parsedContent = computed(() => this.safeParse(this.activeResume()?.content));
  parsedBreakdown = computed(() => this.safeParse(this.activeResume()?.scoreBreakdown));
  parsedMissingSkills = computed<string[]>(() => this.safeParse(this.activeResume()?.missingSkills) || []);

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    public applicationService: JobApplicationService,
    private authService: AuthService,
    private profileService: ProfileService,
    private experienceService: ExperienceService,
    private projectService: ProjectService
  ) {}

  async ngOnInit(): Promise<void> {
    this.applicationId = Number(this.route.snapshot.paramMap.get('id'));
    this.isAdmin = this.authService.getUserRole() === 'admin';
    await Promise.all([this.loadApplication(), this.loadResumes(), this.loadQuota(), this.loadCustomPrompt()]);
    this.loading.set(false);
  }

  isLatest(resume: Resume | null): boolean {
    const list = this.resumes();
    return !!resume && list.length > 0 && list[0].id === resume.id;
  }

  private safeParse(value: any): any {
    if (!value) return null;
    if (typeof value === 'object') return value;
    try {
      return JSON.parse(value);
    } catch {
      return null;
    }
  }

  private async loadApplication(): Promise<void> {
    try {
      const app = await this.applicationService.getApplication(this.applicationId);
      this.application.set(app);
    } catch (error) {
      console.error('Failed to load application:', error);
    }
  }

  private async loadResumes(): Promise<void> {
    try {
      const list = await this.applicationService.listResumes(this.applicationId);
      this.resumes.set(list);
      this.activeResume.set(list[0] || null);
    } catch (error) {
      console.error('Failed to load resumes:', error);
    }
  }

  private async loadQuota(): Promise<void> {
    try {
      this.quota = await firstValueFrom(this.authService.getSubscriptionStatus());
    } catch {
      this.quota = null;
    }
  }

  private async loadCustomPrompt(): Promise<void> {
    if (!this.isAdmin) return;
    try {
      const saved = await this.profileService.getCustomPrompt();
      if (saved) {
        this.customPrompt = saved;
        this.promptDraft = saved;
      }
    } catch (error) {
      console.error('Failed to load custom prompt:', error);
    }
  }

  private showToast(message: string): void {
    this.toast = message;
    setTimeout(() => {
      if (this.toast === message) this.toast = null;
    }, 2200);
  }

  async tailor(): Promise<void> {
    if (this.tailoring()) return;
    this.tailoring.set(true);
    try {
      await this.applicationService.tailorResume(this.applicationId);
      await this.loadResumes();
      this.dirty.set(false);
      this.showToast('Resume tailored successfully!');
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to tailor resume';
      alert(`Tailoring failed: ${msg}`);
    } finally {
      this.tailoring.set(false);
    }
  }

  async reanalyze(): Promise<void> {
    const resume = this.activeResume();
    if (!resume || this.reanalyzing()) return;
    this.reanalyzing.set(true);
    try {
      const result = await this.applicationService.analyzeResume(this.applicationId, resume.id);
      this.activeResume.update((r) => (r ? { ...r, ...result } : r));
      this.resumes.update((list) => list.map((r) => (r.id === resume.id ? { ...r, ...result } : r)));
      this.dirty.set(false);
      this.showToast('Fit analysis updated!');
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to analyze resume';
      alert(`Re-check Fit failed: ${msg}`);
    } finally {
      this.reanalyzing.set(false);
    }
  }

  async regenerateSection(section: SectionKey, index?: number): Promise<void> {
    const resume = this.activeResume();
    if (!resume || !this.isLatest(resume)) return;
    const key = section + (index !== undefined ? ':' + index : '');
    if (this.sectionBusy[key]) return;
    this.sectionBusy[key] = true;
    try {
      const updated = await this.applicationService.regenerateSection(this.applicationId, resume.id, section, index);
      this.activeResume.update((r) => (r ? { ...r, content: updated.content, updatedAt: updated.updatedAt } : r));
      this.resumes.update((list) =>
        list.map((r) => (r.id === resume.id ? { ...r, content: updated.content, updatedAt: updated.updatedAt } : r))
      );
      this.dirty.set(true);
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to regenerate section';
      alert(`Regeneration failed: ${msg}`);
    } finally {
      this.sectionBusy[key] = false;
    }
  }

  onVersionChange(event: Event): void {
    const value = (event.target as HTMLSelectElement).value;
    this.selectVersion(Number(value));
  }

  selectVersion(resumeId: number): void {
    const found = this.resumes().find((r) => r.id === resumeId);
    if (found) this.activeResume.set(found);
  }

  async restore(resumeId: number): Promise<void> {
    if (this.restoringId) return;
    this.restoringId = resumeId;
    try {
      await this.applicationService.restoreResumeVersion(this.applicationId, resumeId);
      await this.loadResumes();
      this.dirty.set(false);
      this.showToast('Version restored as current.');
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to restore version';
      alert(`Restore failed: ${msg}`);
    } finally {
      this.restoringId = null;
    }
  }

  async exportPDF(): Promise<void> {
    const resume = this.activeResume();
    if (!resume || this.exporting()) return;
    this.exporting.set(true);
    try {
      await this.applicationService.downloadResumePDF(this.applicationId, resume.id, `resume-v${resume.version}.pdf`);
    } catch (error) {
      console.error('Failed to export PDF:', error);
      alert('Failed to export PDF.');
    } finally {
      this.exporting.set(false);
    }
  }

  goBack(): void {
    this.router.navigate(['/job-applications']);
  }

  // --- Debug / admin panel (legacy escape hatches, admin-only) ---

  togglePromptEditor(): void {
    this.showPromptEditor = !this.showPromptEditor;
    if (this.showPromptEditor) {
      this.promptDraft = this.customPrompt || this.getDefaultInstructions();
    }
  }

  async saveCustomPrompt(): Promise<void> {
    try {
      this.customPrompt = this.promptDraft.trim();
      await this.profileService.saveCustomPrompt(this.customPrompt);
      this.showPromptEditor = false;
      alert('Custom prompt saved and synced to your account.');
    } catch (error) {
      console.error('Failed to save custom prompt:', error);
      alert('Failed to save custom prompt to database.');
    }
  }

  async resetCustomPrompt(): Promise<void> {
    try {
      this.customPrompt = '';
      await this.profileService.saveCustomPrompt('');
      this.promptDraft = '';
      this.showPromptEditor = false;
      alert('Reverted to default prompt.');
    } catch (error) {
      console.error('Failed to reset custom prompt:', error);
      alert('Failed to reset custom prompt.');
    }
  }

  private getDefaultInstructions(): string {
    return `--- OUTPUT JSON SCHEMA ---
{
  "name": "Full Name",
  "contact": {
    "location": "City, Country",
    "phone": "",
    "email": "",
    "linkedin": "",
    "github": "",
    "portfolio": ""
  },
  "summary": "2-3 sentence professional summary tailored to the job",
  "skills": ["skill1", "skill2", "skill3"],
  "projects": [
    {
      "title": "Project Name",
      "start": "MMM YYYY",
      "end": "MMM YYYY or Present",
      "bullets": ["Impact bullet 1", "Impact bullet 2"],
      "tech": ["tech1", "tech2"]
    }
  ],
  "experience": [
    {
      "company": "Company Name",
      "role": "Position Title",
      "start": "MMM YYYY",
      "end": "MMM YYYY or Present",
      "bullets": ["Achievement with metrics", "Impact statement"]
    }
  ],
  "education": [
    {
      "degree": "Degree",
      "field": "Field of Study",
      "institution": "University Name",
      "start": "MMM YYYY",
      "end": "MMM YYYY or Present"
    }
  ],
  "certifications": [
    { "title": "Certification Title" }
  ]
}

Guidelines:
- Use the provided profile, experience, and projects to populate every section.
- Keep bullets concise, action-oriented, and relevant to the job description.
- Avoid first-person pronouns; ATS-safe wording only.
- No em-dash characters.`;
  }

  async legacyGenerate(): Promise<void> {
    if (this.legacyGenerating) return;
    this.legacyGenerating = true;
    try {
      const prompt = this.customPrompt.trim() || undefined;
      await this.applicationService.generateResume(this.applicationId, undefined, prompt, this.selectedModel);
      await this.loadResumes();
      alert('Legacy resume generated (content only, no analysis).');
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to generate resume';
      alert(`Legacy generation failed: ${msg}`);
    } finally {
      this.legacyGenerating = false;
    }
  }

  async copyPrompt(): Promise<void> {
    const app = this.application();
    if (!app) return;
    try {
      const profile = await this.profileService.getProfile();
      const skills = await this.profileService.getUserSkills();
      const experiences = await this.experienceService.getUserExperiences();
      const projects = await this.projectService.getProjects(false);

      let profileSection = `\n--- USER PROFILE DATA ---\n`;
      if (profile) {
        profileSection += `Name: ${profile.user?.name || 'Not specified'}\n`;
        profileSection += `Email: ${profile.email || profile.user?.email || 'Not specified'}\n`;
        profileSection += `Phone: ${profile.phone || 'Not specified'}\n`;
        profileSection += `Location: ${profile.location || 'Not specified'}\n`;
        profileSection += `LinkedIn: ${profile.linkedin || 'Not specified'}\n`;
        profileSection += `GitHub: ${profile.github || 'Not specified'}\n`;
        profileSection += `Portfolio: ${profile.portfolio || 'Not specified'}\n`;
        if (profile.summary) {
          profileSection += `\nProfessional Summary:\n${profile.summary}\n`;
        }
        if (profile.educations && profile.educations.length > 0) {
          profileSection += `\nEducation:\n`;
          profile.educations.forEach((edu: any) => {
            profileSection += `  - ${edu.degree} in ${edu.field} from ${edu.institution} (${edu.startDate ? new Date(edu.startDate).getFullYear() : ''} - ${edu.endDate ? new Date(edu.endDate).getFullYear() : 'Present'})\n`;
          });
        }
      }

      if (skills && skills.length > 0) {
        profileSection += `\nSkills:\n`;
        skills.forEach((userSkill: any) => {
          profileSection += `  - ${userSkill.skill.name}${userSkill.skill.category ? ` (${userSkill.skill.category})` : ''}${userSkill.level ? ` - ${userSkill.level}` : ''}\n`;
        });
      }

      let experienceSection = `\n--- USER EXPERIENCE ---\n`;
      if (experiences && experiences.length > 0) {
        experiences.forEach((exp: any) => {
          experienceSection += `\nCompany: ${exp.company}\n`;
          experienceSection += `Position: ${exp.position}\n`;
          experienceSection += `Duration: ${exp.startDate ? new Date(exp.startDate).toLocaleDateString() : 'N/A'} - ${exp.endDate ? new Date(exp.endDate).toLocaleDateString() : 'Present'}\n`;
          if (exp.location) experienceSection += `Location: ${exp.location}\n`;
          if (exp.description) experienceSection += `Description: ${exp.description}\n`;
          if (exp.bullets && exp.bullets.length > 0) {
            experienceSection += `Key Achievements:\n`;
            exp.bullets.forEach((bullet: any) => {
              experienceSection += `  - ${bullet.content}\n`;
            });
          }
        });
      } else {
        experienceSection += `No experience data available.\n`;
      }

      let projectSection = `\n--- USER PROJECTS ---\n`;
      if (projects && projects.length > 0) {
        projects.filter((p: any) => !p.archived).forEach((proj: any) => {
          projectSection += `\nProject: ${proj.title}\n`;
          if (proj.summary) projectSection += `Summary: ${proj.summary}\n`;
          if (proj.role) projectSection += `Role: ${proj.role}\n`;
          if (proj.techStack) {
            projectSection += `Technologies: ${proj.techStack}\n`;
          }
          if (proj.bullets && proj.bullets.length > 0) {
            projectSection += `Key Features/Achievements:\n`;
            proj.bullets.forEach((bullet: any) => {
              projectSection += `  - ${bullet.content}\n`;
            });
          }
          if (proj.url) projectSection += `URL: ${proj.url}\n`;
          if (proj.startDate) {
            projectSection += `Duration: ${new Date(proj.startDate).toLocaleDateString()} - ${proj.endDate ? new Date(proj.endDate).toLocaleDateString() : 'Present'}\n`;
          }
        });
      } else {
        projectSection += `No project data available.\n`;
      }

      const defaultInstructions = this.getDefaultInstructions();
      const instructions = this.customPrompt.trim() || defaultInstructions;

      const prompt = `You are an expert ATS resume writer. Generate a concise, ATS-safe resume in JSON format using the exact schema below. Use month-year for dates (e.g., Jan 2024). Avoid fancy formatting.

--- JOB TARGET ---
Job Title: ${app.jobTitle}
Job Description:
${app.jobDescription}
${profileSection}${experienceSection}${projectSection}

${instructions}`;

      await navigator.clipboard.writeText(prompt);
      alert('Detailed prompt with your profile data copied to clipboard! Paste it into ChatGPT.');
    } catch (err) {
      console.error('Failed to copy:', err);
      alert('Failed to copy prompt. Please try again.');
    }
  }

  startImport(): void {
    this.importingOpen = true;
    this.importContent = '';
  }

  cancelImport(): void {
    this.importingOpen = false;
    this.importContent = '';
  }

  async submitImport(): Promise<void> {
    if (!this.importContent.trim()) {
      alert('Please paste resume JSON content.');
      return;
    }
    try {
      await this.applicationService.importResume(this.applicationId, this.importContent);
      await this.loadResumes();
      this.cancelImport();
      alert('Resume imported successfully!');
    } catch (error: any) {
      const msg = error?.error?.error || error?.message || 'Failed to import resume.';
      alert(`Import failed: ${msg}`);
    }
  }

  toggleRaw(): void {
    this.showRaw = !this.showRaw;
  }
}
