import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="legal-page">
      <div class="legal-card">
        <a routerLink="/pricing" class="back-link">← Back</a>
        <h1>Terms of Service</h1>
        <p class="last-updated">Last updated: 1 July 2026</p>

        <h2>1. Service</h2>
        <p>RoleFit ("we", "us") is a resume-tailoring tool operated by an individual developer. Access requires a paid monthly subscription of RM29.</p>

        <h2>2. Account</h2>
        <p>You are responsible for keeping your login credentials confidential and for all activity under your account.</p>

        <h2>3. Subscription & Payment</h2>
        <p>Subscriptions are billed monthly via ToyyibPay. Your subscription begins when payment is confirmed and expires 30 days later. It does not renew automatically.</p>

        <h2>4. AI-Generated Content</h2>
        <p>Resume content is generated by Google Gemini AI. We do not guarantee accuracy. You are responsible for reviewing all AI-generated content before submitting it to any employer.</p>

        <h2>5. Acceptable Use</h2>
        <p>You may not misuse the service, attempt to circumvent usage limits, or use the service for unlawful purposes.</p>

        <h2>6. Limitation of Liability</h2>
        <p>The service is provided "as is." We are not liable for any outcomes related to your job search or the accuracy of AI-generated content.</p>

        <h2>7. Changes</h2>
        <p>We may update these terms. Continued use of the service after changes constitutes acceptance.</p>

        <h2>8. Contact</h2>
        <p>Questions? Email us at <a href="mailto:support@rolefit.my">support@rolefit.my</a></p>
      </div>
    </div>
  `,
  styles: [`
    .legal-page {
      min-height: 100vh;
      background: #f5f7fa;
      padding: 2rem 1rem;
    }
    .legal-card {
      max-width: 680px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      padding: 2rem;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }
    .back-link { color: #667eea; text-decoration: none; font-size: 0.9rem; }
    h1 { margin: 1rem 0 0.25rem; }
    .last-updated { color: #888; font-size: 0.85rem; margin: 0 0 2rem; }
    h2 { color: #333; font-size: 1.1rem; margin-top: 1.5rem; }
    p { color: #555; line-height: 1.6; }
    a { color: #667eea; }
  `]
})
export class TermsComponent {}
